<div class="chatlog__message-group">
  <div id="chatlog__message-container-1000969484456177754" class="chatlog__message-container" data-message-id="1000969484456177754">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__reference-symbol"></div><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/982906333424652348/8778503bce01c3814ae2081a81dd57c0.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__reference"><img class="chatlog__reference-avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=512" alt="Avatar" loading="lazy">
          <div class="chatlog__reference-author" style="color:rgb(17,128,106)" title="koher#9336">koher</div>
          <div class="chatlog__reference-content"><span class="chatlog__reference-link" onclick="scrollToMessage(event,'1000969483134980138')"> 伝播の実験 <span class="chatlog__markdown-mention" title="swift57#4949">@swift-5.7.1-dev</span>
              <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">@rethrows protocol P { func foo() throws } @rethrows protocol Q { associatedtype PType1: P associatedtype PType2: P func makeP1() -&gt; PType1 func makeP2() -&gt; PType2 } struct S1: P { func foo() { print("S1") } } struct S2: P { func foo() throws { print("S2") } } struct T1: Q { func makeP1() -&gt; S1 { S1() } func makeP2() -&gt; S2 { S2() } } struct T2: Q { func makeP1() -&gt; S2 { S2() } func makeP2() -&gt; S1 { S1() } } func callFooOfP1&lt;T: Q&gt;(from q: T) rethrows { try q.makeP1().foo() } callFooOfP1(from: T1()) do { try callFooOfP1(from: T2()) } catch { print(error) }</code> </span></div>
        </div>
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(52,152,219)" title="swift57#4949" data-user-id="982906333424652348">swift57</span> <span class="chatlog__bot-label">BOT</span> <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=1000969484456177754"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-1000969484456177754">25-Jul-22 03:35 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">exit status: 1 with stderr:<code class="chatlog__markdown-pre chatlog__markdown-pre--multiline nohighlight">&lt;stdin&gt;:48:1: error: call can throw but is not marked with 'try' callFooOfP1(from: T1()) ^~~~~~~~~~~~~~~~~~~~~~~ &lt;stdin&gt;:48:1: note: call is to 'rethrows' function, but a conformance has a throwing witness callFooOfP1(from: T1()) ^</code></span></div>
      </div>
    </div>
  </div>
</div>