<div class="chatlog__message-group">
  <div id="chatlog__message-container-1169432691893076008" class="chatlog__message-container" data-message-id="1169432691893076008">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__reply-symbol"></div><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/357858243869016065/afb20eab67082201bd227d98d3fb7596.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__reply"><img class="chatlog__reply-avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=512" alt="Avatar" loading="lazy">
          <div class="chatlog__reply-author" style="color:rgb(237,171,161)" title="omochimetaru">omochimetaru</div>
          <div class="chatlog__reply-content"><span class="chatlog__reply-link" onclick="scrollToMessage(event,'1169430877231665285')"> non isolated funcに飛ぶ時に切り替わるか、ではなくて、戻ってこれるかになってますね </span></div>
        </div>
        <div class="chatlog__header"><span class="chatlog__author" title="kntk" data-user-id="357858243869016065">kntk</span> <a href="/channels/430242233468452865?category=main&amp;channel=swiftbot-sandbox&amp;message_id=1169432691893076008"><span class="chatlog__timestamp" title="Thursday, November 2, 2023 12:28 AM"></span></a><a href="#chatlog__message-container-1169432691893076008">11/2/2023 12:28 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">バグの件はそうなんですが SE-0338によると <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">It calls some other async function which then returns, resuming the caller.</code> と戻ってくるケースも引き継ぐと書いてあるので true, falseになれば引き継がれることが証明できるかなと思ったんですが、mainがMainActorじゃダメですね... static func main() async { print(Thread.isMainThread) await isolatedFunc() print(Thread.isMainThread) }</span></div>
      </div>
    </div>
  </div>
</div>