<div class="chatlog__message-group">
  <div id="chatlog__message-container-348418967465099265" class="chatlog__message-container" data-message-id="348418967465099265">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(237,171,161)" title="omochimetaru#1122" data-user-id="189711109966659584">omochimetaru</span> <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=348419600934895618"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-348418967465099265">19-Aug-17 10:52 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">bodyのsuspend後に発生するthrowについては、beginAsyncのrethrowsとは関係ないですね</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-348419019503697920" class="chatlog__message-container" data-message-id="348419019503697920">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="19-Aug-17 10:52 AM">10:52</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">/// If the async process completes by /// throwing an error before suspending itself, <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">beginAsync</code> rethrows the error.</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-348419182397882370" class="chatlog__message-container" data-message-id="348419182397882370">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="19-Aug-17 10:53 AM">10:53</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">beginAsyncのドキュメントには、suspend後の再開後についてのエラーがどうなるか書いてないですね</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-348419600934895618" class="chatlog__message-container" data-message-id="348419600934895618">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="19-Aug-17 10:55 AM">10:55</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">今の状態は、 suspend前のthrowをrethrowsして、suspend後については書いてない <span class="chatlog__markdown-mention" title="koher#9336">@koher</span> の案は、 suspend後も前もthrow禁止にして、ユーザ側の昇格に任せる</span></div>
      </div>
    </div>
  </div>
</div>