<div class="chatlog__message-group">
  <div id="chatlog__message-container-402641380704256018" class="chatlog__message-container" data-message-id="402641380704256018">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(17,128,106)" title="koher" data-user-id="293624673265123328">koher</span> <a href="/channels/387857770038427648?category=main&amp;channel=testing&amp;message_id=402641500497772549"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-402641380704256018">01/16/2018 1:53 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">はい、↓のようなケースで、 <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">x</code> に負の数を入れて正しくエラーになることをテストしたいです。 <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">func foo(_ x: Int) { preconditon(x &gt;= 0) // x を使う処理 }</code></span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-402641500497772549" class="chatlog__message-container" data-message-id="402641500497772549">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="01/16/2018 1:53 AM">01:53</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">Java だと <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">RuntimeException</code> なので <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">catch</code> できるんですが・・・。</span></div>
      </div>
    </div>
  </div>
</div>