<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/296587674737704960/5d3c584499ce245b7129cda8c7ae00e9.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="rintaro#0001" data-user-id="296587674737704960" style="">rintaro</span>
    <span class="chatlog__timestamp">02-Oct-18 05:39 AM</span>
    <div class="chatlog__message " data-message-id="496556759385636906" id="message-496556759385636906" title="Message sent: 02-Oct-18 05:39 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">step out 時の return value キャプチャ は Swift で動かないっぽいんですが、なぜか throw はキャプチャできました。 throws な func の適当なところにブレークポイントはって、ブレークした状態で、 Step out で進めると func 抜けたところで止まります。んで、<span class="pre pre--inline">thread info</span> コマンドを実行すると <span class="pre pre--inline">Return value: (CommandLineSandbox.MyError) $E0 = fooError</span> みたいな行が表示されているので、<span class="pre pre--inline">po $E0</span> とかで中身が見られます。</span>
        </div>
      </div>
    </div>
  </div>
</div>