<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="omochimetaru#1122" data-user-id="189711109966659584" style="color: rgb(237,171,161)">omochimetaru</span>
    <span class="chatlog__timestamp">22-Oct-18 04:20 AM</span>
    <div class="chatlog__message " data-message-id="503784607519604736" id="message-503784607519604736" title="Message sent: 22-Oct-18 04:20 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">SwiftってdeinitがあるからRAIIパターンが書けるっていうメリットがあるとされてると思うんですが、 例えばinitでファイルハンドルを開いてdeinitで閉じるようなパターンを実装する時、 閉じるときに生じた例外をハンドリングできないという問題があると思ってて それについて最近思ったのが、 deinitがthrowsつけられてもよいのでは？ということで そうすると、throwing deinitな型をスコープに持っている関数がthrows化するのと、 そういう型の var に対する代入文が throws化するんだけど、 どう思います？</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="503784880757276682" id="message-503784880757276682" title="Message sent: 22-Oct-18 04:21 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">
            <div class="pre pre--multiline language-swift">func writeData() throws { // ここにclose失敗のthrowsが必要, スコープ脱出時だからtry catchはできない let stream = try OutputStream() try stream.write("aaa") }</div>
          </span>
          <span class="chatlog__edited-timestamp" title="22-Oct-18 04:21 AM">(edited)</span>
        </div>
      </div>
    </div>
  </div>
</div>