<div class="chatlog__message-group">
  <div class="chatlog__author-avatar-container">
    <img class="chatlog__author-avatar" src="https://cdn.discordapp.com/avatars/189711109966659584/95280765d1be73ce985dce15ea3585f6.png?size=128" alt="Avatar" loading="lazy">
  </div>
  <div class="chatlog__messages">
    <span class="chatlog__author-name" title="omochimetaru#1122" data-user-id="189711109966659584" style="color: rgb(237,171,161)">omochimetaru</span>
    <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=635802718560059403"><span class="chatlog__timestamp">21-Oct-19 11:31 AM</span></a>
    <div class="chatlog__message " data-message-id="635802221807927316" id="message-635802221807927316" title="Message sent: 21-Oct-19 11:31 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">例えば</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802327051403284" id="message-635802327051403284" title="Message sent: 21-Oct-19 11:31 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">
            <div class="pre pre--multiline language-java">class A { typealias Error = NumberFormatException | IOException; void f() throws Error { } }</div>
          </span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802396282454017" id="message-635802396282454017" title="Message sent: 21-Oct-19 11:31 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">こういう状況で、f()を呼び出して、そのままthrowsする関数をAのユーザーが作ったときに</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802451705856000" id="message-635802451705856000" title="Message sent: 21-Oct-19 11:31 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace"><span class="pre pre--inline">A.Error</span>で再throwsを書ければ</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802484031488000" id="message-635802484031488000" title="Message sent: 21-Oct-19 11:32 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">将来A.Errorの右辺が変更したときも</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802530646982686" id="message-635802530646982686" title="Message sent: 21-Oct-19 11:32 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">「Aのエラーをそのまま再throws」っていう意味の記述が維持できるけど</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802612150566933" id="message-635802612150566933" title="Message sent: 21-Oct-19 11:32 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">typealiasが無いと、再throwsする関数のシグネチャも直さないといけない</span>
        </div>
      </div>
    </div>
    <div class="chatlog__message " data-message-id="635802718560059403" id="message-635802718560059403" title="Message sent: 21-Oct-19 11:33 AM">
      <div class="chatlog__content">
        <div class="markdown">
          <span class="preserve-whitespace">そういう意味でAのユーザーにとってA.Errorの実体を無視することを許すのでカプセル化？かなと</span>
        </div>
      </div>
    </div>
  </div>
</div>