<div class="chatlog__message-group">
  <div id="chatlog__message-container-810790649871728720" class="chatlog__message-container" data-message-id="810790649871728720">
    <div class="chatlog__message">
      <div class="chatlog__message-aside"><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/293572563010060288/92f572b5e1ef6656a55498787c15a5ad.png?size=512" alt="Avatar" loading="lazy"></div>
      <div class="chatlog__message-primary">
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(231,76,60)" title="tarunon" data-user-id="293572563010060288">tarunon</span> <a href="/channels/291054454793306112?category=main&amp;channel=swift&amp;message_id=810790886426017813"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-810790649871728720">02/15/2021 8:32 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">UnsafeContinuation&lt;T&gt;にして <code class="chatlog__markdown-pre chatlog__markdown-pre--multiline language-swift">func withUnsafeContinuation&lt;T&gt;( operation: (UnsafeContinuation&lt;T, Never&gt;) -&gt; () ) async -&gt; T func withUnsafeThrowingContinuation&lt;T, E: Error&gt;( operation: (UnsafeContinuation&lt;Result&lt;T, E&gt;&gt;) throws -&gt; () ) async throws -&gt; T</code> にすれば、throwsで受けることもResultで受けることもできそうだ</span></div>
      </div>
    </div>
  </div>
  <div id="chatlog__message-container-810790886426017813" class="chatlog__message-container" data-message-id="810790886426017813">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__short-timestamp" title="02/15/2021 8:33 AM">08:33</div>
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">でもContinuationだから継続の話ですよね、だとするとError発生は中断させたいはずで、Result入れ子は不適切だと思う</span></div>
      </div>
    </div>
  </div>
</div>