<div class="chatlog__message-group">
  <div id="chatlog__message-container-881494625515356190" class="chatlog__message-container " data-message-id="881494625515356190">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__reference-symbol"></div>
        <img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__reference">
          <img class="chatlog__reference-avatar" src="https://cdn.discordapp.com/avatars/291062140079570944/75d22639a88c37be90cb60118acb7df5.png?size=512" alt="Avatar" loading="lazy">
          <div class="chatlog__reference-author" style="color: rgb(241, 196, 15)" title="kateinoigakukun#2184">kateinoigakukun</div>
          <div class="chatlog__reference-content">
            <span class="chatlog__reference-link" onclick="scrollToMessage(event, '881494144281886751')"> キャンセルされたかどうかはthrowされたエラーで決められるのではなく、 <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">cancel</span> メソッドを呼んだレシーバのTaskに対してキャンセルフラグが立つ実装になっています。 </span>
          </div>
        </div>
        <div class="chatlog__header">
          <span class="chatlog__author" style="color: rgb(17, 128, 106)" title="koher#9336" data-user-id="293624673265123328">koher</span>
          <span class="chatlog__timestamp">29-Aug-21 11:04 AM</span>
        </div>
        <div class="chatlog__content chatlog__markdown">
          <span class="chatlog__markdown-preserve">
            <div class="chatlog__markdown-quote">
              <div class="chatlog__markdown-quote-border"></div>
              <div class="chatlog__markdown-quote-content"> cancel メソッドを呼んだレシーバのTaskに対してキャンセルフラグが立つ実装 </div>
            </div>それを受けて、非同期 API 実装側は <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">Task.checkCancellation()</span> を呼ぶか、 <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">Task.isCancelled</span> をチェックして適切な処理を行った後に <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">CancellationError</span> を <span class="chatlog__markdown-pre chatlog__markdown-pre--inline">throw</span> するというルールなのかと思っていました。
          </span>
        </div>
      </div>
    </div>
  </div>
</div>