<div class="chatlog__message-group">
  <div id="chatlog__message-container-881494625515356190" class="chatlog__message-container" data-message-id="881494625515356190">
    <div class="chatlog__message">
      <div class="chatlog__message-aside">
        <div class="chatlog__reply-symbol"></div><img class="chatlog__avatar" src="https://cdn.discordapp.com/avatars/293624673265123328/accd07acc220a18568ba46a6e9ede18a.png?size=512" alt="Avatar" loading="lazy">
      </div>
      <div class="chatlog__message-primary">
        <div class="chatlog__reply"><img class="chatlog__reply-avatar" src="https://cdn.discordapp.com/avatars/291062140079570944/75d22639a88c37be90cb60118acb7df5.png?size=512" alt="Avatar" loading="lazy">
          <div class="chatlog__reply-author" style="color:rgb(241,196,15)" title="kateinoigakukun#2184">kateinoigakukun</div>
          <div class="chatlog__reply-content"><span class="chatlog__reply-link" onclick="scrollToMessage(event,'881494144281886751')"> キャンセルされたかどうかはthrowされたエラーで決められるのではなく、 <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">cancel</code> メソッドを呼んだレシーバのTaskに対してキャンセルフラグが立つ実装になっています。 </span></div>
        </div>
        <div class="chatlog__header"><span class="chatlog__author" style="color:rgb(17,128,106)" title="koher" data-user-id="293624673265123328">koher</span> <a href="/channels/306995750418513920?category=main&amp;channel=swift-2&amp;message_id=881494625515356190"><span class="chatlog__timestamp"></span></a><a href="#chatlog__message-container-881494625515356190">08/29/2021 11:04 AM</a></div>
        <div class="chatlog__content chatlog__markdown"><span class="chatlog__markdown-preserve">
            <div class="chatlog__markdown-quote">
              <div class="chatlog__markdown-quote-border"></div>
              <div class="chatlog__markdown-quote-content"> cancel メソッドを呼んだレシーバのTaskに対してキャンセルフラグが立つ実装 </div>
            </div>それを受けて、非同期 API 実装側は <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">Task.checkCancellation()</code> を呼ぶか、 <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">Task.isCancelled</code> をチェックして適切な処理を行った後に <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">CancellationError</code> を <code class="chatlog__markdown-pre chatlog__markdown-pre--inline">throw</code> するというルールなのかと思っていました。
          </span></div>
      </div>
    </div>
  </div>
</div>